security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
crdp:
  host: ${ORDS_HOST}
  in-file-dir: ${INCOMING_FILE_DIR}
  rabbitmq:
    ords-host: ${ORDS_HOST}
    receiver-queue: ${RECEIVER_QUEUE_NAME}
    receiver-routing-key: ${RECEIVER_ROUTING_KEY}
    ping-queue: ${PING_QUEUE_NAME}
    ping-routing-key: ${PING_ROUTING_KEY}
    exchange-name: ${RABBIT_EXCHANGE_NAME}

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
