security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
crdp:
  host: ${ORDS_HOST}
  in-progress-dir: ${IN_PROGRESS_DIR}
  completed-dir: ${COMPLETED_DIR}
  errors-dir: ${ERRORS_DIR}
  scanner-queue: ${SCANNER_QUEUE_NAME}
  sftp-enabled: ${SFTP_ENABLED}

bcgov:
  sftp:
    host: ${SFEG_HOST:localhost}
    port: ${SFEG_PORT:22}
    username: ${SFEG_USERNAME}
    remote-location: ${NFS_DIR:/}
    known-hosts-file-name: ${SFTP_KNOWN_HOSTS}
    ssh-private-key: ${SFTP_PRIVATE_KEY}

spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health

