security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
crdp:
  host: ${ORDS_HOST}
  cron-job-outgoing-file:  ${CRON_JOB_OUTGOING_FILE}
  rabbitmq:
    receiver-queue: ${RECEIVER_QUEUE_NAME}
    receiver-routing-key: ${RECEIVER_ROUTING_KEY}
    exchange-name: ${RABBIT_EXCHANGE_NAME}

spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health

server:
  port: 8081
