apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${COMPONENT_NAME}
  description: Deployment template for the JAG-CRDP-TRANSMIT-RECEIVER
  
labels:
  app: ${APP_NAME}
  app.kubernetes.io/name: ${COMPONENT_NAME}
  app.kubernetes.io/part-of: ${APP_GROUP}
  app.openshift.io/runtime: ${RUNTIME}
  
parameters:

- name: APP_NAME
  description: The application name that each component is part of
  required: false
  value: jag-crdp

- name: COMPONENT_NAME
  description: The application name
  required: false
  value: jag-crdp-transmit-receiver

- name: APP_GROUP
  description: The group name that this component is part of
  required: false
  value: jag-crdp-transmit
  
- name: OC_NAMESPACE
  description: The OpenShift namespace prefix
  required: false
  # Below value must be changed as per gold cluster oc nameplate
  value: da81c0
  
- name: OC_ENV
  description: The OpenShift environment, ie dev, test or prod
  required: true

- name: RUNTIME
  description: The application name that each component is part of
  required: false
  value: java

- name: AUTH_HEADER
  description: The http Authorization header required for performing livenessProbe & readinessProbe in deployment config during container start.
  required: true
  value: ''
  
objects:

### JAG-CRDP-TRANSMIT-RECEIVER Deployment Config ###
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: ${COMPONENT_NAME}
    namespace: ${OC_NAMESPACE}-${OC_ENV}
      
  spec:
    completionDeadlineSeconds: 1200
    replicas: 3
    selector:
      name: ${COMPONENT_NAME}
    strategy:
      type: Rolling
      maxSurge: 50%
      maxUnavailable: 0
    template:
      metadata:
        labels:
          name: ${COMPONENT_NAME}
      spec:
        containers:
          - image: >-
              image-registry.openshift-image-registry.svc:5000/${OC_NAMESPACE}-tools/${COMPONENT_NAME}:${OC_ENV}
            name: ${COMPONENT_NAME} 
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            env:
              - name: BASIC_AUTH_USER
                valueFrom:
                  secretKeyRef:
                    name: ${COMPONENT_NAME}
                    key: BASIC_AUTH_USER
              - name: BASIC_AUTH_PASS
                valueFrom:
                  secretKeyRef:
                    name: ${COMPONENT_NAME}
                    key: BASIC_AUTH_PASS
              - name: SPRING_PROFILES_ACTIVE
                valueFrom:
                  secretKeyRef:
                    name: ${COMPONENT_NAME}
                    key: SPRING_PROFILE
              - name: ORDS_HOST
                valueFrom:
                  secretKeyRef:
                    name: ${COMPONENT_NAME}
                    key: ORDS_HOST
              - name: CRON_JOB_OUTGOING_FILE
                valueFrom:
                  secretKeyRef:
                    name: ${COMPONENT_NAME}
                    key: CRON_JOB_OUTGOING_FILE
              - name: RABBIT_EXCHANGE_NAME
                valueFrom:
                  secretKeyRef:
                    name: ${COMPONENT_NAME}
                    key: RABBIT_EXCHANGE_NAME
              - name: RABBIT_MQ_HOST
                valueFrom:
                  secretKeyRef:
                    name: ${COMPONENT_NAME}
                    key: RABBIT_MQ_HOST
              - name: RECEIVER_QUEUE_NAME
                valueFrom:
                  secretKeyRef:
                    name: ${COMPONENT_NAME}
                    key: RECEIVER_QUEUE_NAME
              - name: RECEIVER_ROUTING_KEY
                valueFrom:
                  secretKeyRef:
                    name: ${COMPONENT_NAME}
                    key: RECEIVER_ROUTING_KEY
              - name: RABBIT_MQ_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: rabbitmq-cluster-secret
                    key: username
              - name: RABBIT_MQ_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: rabbitmq-cluster-secret
                    key: password
              - name: SPLUNK_HTTP_URL
                valueFrom:
                  secretKeyRef:
                    name: crdp-splunk-config
                    key: SPLUNK_HTTP_URL
              - name: SPLUNK_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: crdp-splunk-config
                    key: SPLUNK_TOKEN
              - name: SPLUNK_INDEX
                valueFrom:
                  secretKeyRef:
                    name: crdp-splunk-config
                    key: SPLUNK_INDEX
            resources:
              limits:
                cpu: 100m
                memory: 200Mi
              requests:
                cpu: 50m
                memory: 100Mi
            livenessProbe:
              httpGet:
                path: "/actuator/health"
                port: 8080
                scheme: HTTP
                httpHeaders:
                - name: Authorization
                  value: ${AUTH_HEADER}
              initialDelaySeconds: 100
              timeoutSeconds: 30
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: "/actuator/health"
                port: 8080
                scheme: HTTP
                httpHeaders:
                - name: Authorization
                  value: ${AUTH_HEADER}
              initialDelaySeconds: 100
              timeoutSeconds: 30
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${COMPONENT_NAME}
          from:
            kind: ImageStreamTag
            namespace: ${OC_NAMESPACE}-tools
            name: ${COMPONENT_NAME}:${OC_ENV}

### JAG-CRDP-TRANSMIT-RECEIVER Service ###
- apiVersion: v1
  kind: Service
  metadata:
    name: ${COMPONENT_NAME}
    namespace: ${OC_NAMESPACE}-${OC_ENV}
  spec:
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 8080
    selector:
      name: ${COMPONENT_NAME}
    sessionAffinity: None
    type: ClusterIP
