security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
crdp:
  in-file-dir: ${INCOMING_FILE_DIR}
  in-progress-dir: ${IN_PROGRESS_DIR}
  cron-job-incomming-file:  ${CRON_JOB_INCOMING_FILE}
  rabbitmq:
    scanner-queue: ${SCANNER_QUEUE_NAME}
    scanner-routing-key: ${SCANNER_ROUTING_KEY}
    exchange-name: ${RABBIT_EXCHANGE_NAME}

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health

server:
  port: 8083
