security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
crdp:
  host: ${ORDS_HOST}
  in-file-dir: ${INCOMING_FILE_DIR}
  out-file-dir: ${OUTGOING_FILE_DIR}
  notification-addresses: ${NOTIFICATION_ADDR}
  smtp-from: ${SMTP_FROM}
  cron-job-incomming-file:  ${CRON_JOB_INCOMMING_FILE}
  cron-job-outgoing-file:  ${CRON_JOB_OUTGOING_FILE}

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
