# This workflow is used to build & scan image using trivy vulnerability scanner and upload the results to github security tab

name: Build & Vulnerability Scan using Trivy Scanner

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, release/* ]
  workflow_dispatch:
    branches: [ main, release/*]

jobs:
  build-scan-image:
    name: Build & Scan Image
    runs-on: ubuntu-20.04
    env:
      BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
      BASIC_AUTH_PASS: ${{ secrets.BASIC_AUTH_PASS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK build environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Runs build steps
      - name: Maven Package
        run: mvn -ntp clean package

      - name: Maven Verify
        run: mvn -ntp clean verify

      - name: Build image jag-crdp-transmit-receiver from Dockerfile
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: ./jag-crdp-transmit-receiver
        run: |
          docker build -t docker.io/crdp/jag-crdp-transmit-receiver:${{ github.sha }} ${CONTEXT}

      # Run Vulnerability Scan using Trivy scanner
      - name: Run Trivy vulnerability scanner for jag-crdp-transmit-receiver image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: docker.io/crdp/jag-crdp-transmit-receiver:${{ github.sha }}
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL

      - name: Build image jag-crdp-transmit-sender from Dockerfile
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: ./jag-crdp-transmit-sender
        run: |
          docker build -t docker.io/crdp/jag-crdp-transmit-sender:${{ github.sha }} ${CONTEXT}

      # Run Vulnerability Scan using Trivy scanner
      - name: Run Trivy vulnerability scanner for jag-crdp-transmit-sender image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: docker.io/crdp/jag-crdp-transmit-sender:${{ github.sha }}
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL

      - name: Build image jag-crdp-process-scanner from Dockerfile
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: ./jag-crdp-process-scanner
        run: |
          docker build -t docker.io/crdp/jag-crdp-process-scanner:${{ github.sha }} ${CONTEXT}

      # Run Vulnerability Scan using Trivy scanner
      - name: Run Trivy vulnerability scanner for jag-crdp-process-scanner image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: docker.io/crdp/jag-crdp-process-scanner:${{ github.sha }}
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL

      - name: Build image jag-crdp-process-transformer from Dockerfile
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: ./jag-crdp-process-transformer
        run: |
          docker build -t docker.io/crdp/jag-crdp-process-transformer:${{ github.sha }} ${CONTEXT}

      # Run Vulnerability Scan using Trivy scanner
      - name: Run Trivy vulnerability scanner for jag-crdp-process-transformer image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: docker.io/crdp/jag-crdp-process-transformer:${{ github.sha }}
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL

      # Upload results to the Github security tab.
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: trivy-results.sarif
